mod clients;
mod clipboard_paste;
mod config;
mod error;
mod keyboard_listener;
mod keychain;
mod recording;
mod setup;
mod sound_player;
mod tauri_commands;
mod ui;
mod updater;

/// Build the tauri-specta builder for type-safe commands
fn build_specta_builder() -> tauri_specta::Builder<tauri::Wry> {
    tauri_specta::Builder::<tauri::Wry>::new()
        // Commands with specta support (type-safe bindings will be generated)
        .commands(tauri_specta::collect_commands![
            // App configuration
            tauri_commands::load_app_config,
            tauri_commands::save_app_config,
            // OpenAI provider
            tauri_commands::load_openai_config,
            tauri_commands::save_openai_config,
            tauri_commands::delete_openai_config,
            tauri_commands::test_openai_config,
            // Azure OpenAI provider
            tauri_commands::load_azure_openai_config,
            tauri_commands::save_azure_openai_config,
            tauri_commands::delete_azure_openai_config,
            tauri_commands::test_azure_openai_config,
            // Recording
            tauri_commands::stop_recording,
            tauri_commands::cancel_recording,
            tauri_commands::retry_transcription,
            tauri_commands::dismiss_error,
            tauri_commands::resize_popup_for_error,
            tauri_commands::register_audio_level_channel,
            // Updater
            updater::check_for_updates,
        ])
}

pub fn run() {
    // Load environment variables from .env file
    dotenvy::dotenv().ok();

    // Build specta for type generation
    let specta_builder = build_specta_builder();

    // Export TypeScript bindings in debug mode
    #[cfg(debug_assertions)]
    specta_builder
        .export(
            specta_typescript::Typescript::default()
                .header("// @ts-nocheck\n// Auto-generated by tauri-specta. DO NOT EDIT.\n"),
            "../src/bindings.ts",
        )
        .expect("Failed to export TypeScript bindings");

    tauri::Builder::default()
        .plugin(tauri_plugin_store::Builder::new().build())
        .plugin(tauri_plugin_updater::Builder::new().build())
        .plugin(tauri_plugin_dialog::init())
        .plugin(tauri_plugin_process::init())
        .plugin(tauri_plugin_opener::init())
        .setup(|app| setup::setup_app(app))
        // Note: specta_builder is only used for TypeScript generation (export above)
        // All commands still go through generate_handler! for runtime
        .invoke_handler(tauri::generate_handler![
            tauri_commands::check_accessibility_permission,
            tauri_commands::request_accessibility_permission,
            tauri_commands::restart_app,
            tauri_commands::stop_recording,
            tauri_commands::cancel_recording,
            // App configuration
            tauri_commands::load_app_config,
            tauri_commands::save_app_config,
            // OpenAI provider
            tauri_commands::load_openai_config,
            tauri_commands::save_openai_config,
            tauri_commands::delete_openai_config,
            tauri_commands::test_openai_config,
            // Azure OpenAI provider
            tauri_commands::load_azure_openai_config,
            tauri_commands::save_azure_openai_config,
            tauri_commands::delete_azure_openai_config,
            tauri_commands::test_azure_openai_config,
            // Audio
            tauri_commands::register_audio_level_channel,
            // Error handling
            tauri_commands::retry_transcription,
            tauri_commands::dismiss_error,
            tauri_commands::resize_popup_for_error,
            // Updater
            updater::check_for_updates
        ])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
