use crate::{models, recording, shortcuts, with_commands};

/// Setup Specta for type-safe TypeScript bindings and event emission
///
/// This function:
/// - Registers all commands and events with Specta
/// - Exports TypeScript bindings (debug mode only)
/// - Mounts events to Tauri for runtime emission
pub fn setup(app: &tauri::AppHandle) {
    let builder = tauri_specta::Builder::<tauri::Wry>::new()
        // Commands with specta support (type-safe bindings will be generated)
        .commands(with_commands!(tauri_specta::collect_commands))
        // Events with specta support (type-safe bindings will be generated)
        .events(tauri_specta::collect_events![
            recording::events::RecordingStateChanged,
            // Model events (discriminated unions for state machine patterns)
            models::events::ModelDownloadStateChanged,
            models::events::ModelLoadingStateChanged,
            // Shortcuts events
            shortcuts::events::KeyCaptureEvent,
        ]);

    // Export TypeScript bindings in debug mode
    #[cfg(debug_assertions)]
    builder
        .export(
            specta_typescript::Typescript::default()
                .bigint(specta_typescript::BigIntExportBehavior::Number)
                .header("// @ts-nocheck\n// Auto-generated by tauri-specta. DO NOT EDIT.\n"),
            "../src/bindings.ts",
        )
        .expect("Failed to export TypeScript bindings");

    // Mount events to Tauri for runtime emission
    builder.mount_events(app);
}
