/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecordingPopupRouteRouteImport } from './routes/recording-popup/route'
import { Route as PreferencesRouteRouteImport } from './routes/preferences/route'
import { Route as RecordingPopupIndexRouteImport } from './routes/recording-popup/index'
import { Route as PreferencesIndexRouteImport } from './routes/preferences/index'
import { Route as PreferencesUpdatesRouteImport } from './routes/preferences/updates'
import { Route as PreferencesApiKeysRouteImport } from './routes/preferences/api-keys'
import { Route as PreferencesAboutRouteImport } from './routes/preferences/about'

const RecordingPopupRouteRoute = RecordingPopupRouteRouteImport.update({
  id: '/recording-popup',
  path: '/recording-popup',
  getParentRoute: () => rootRouteImport,
} as any)
const PreferencesRouteRoute = PreferencesRouteRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordingPopupIndexRoute = RecordingPopupIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RecordingPopupRouteRoute,
} as any)
const PreferencesIndexRoute = PreferencesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PreferencesRouteRoute,
} as any)
const PreferencesUpdatesRoute = PreferencesUpdatesRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => PreferencesRouteRoute,
} as any)
const PreferencesApiKeysRoute = PreferencesApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => PreferencesRouteRoute,
} as any)
const PreferencesAboutRoute = PreferencesAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PreferencesRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/preferences': typeof PreferencesRouteRouteWithChildren
  '/recording-popup': typeof RecordingPopupRouteRouteWithChildren
  '/preferences/about': typeof PreferencesAboutRoute
  '/preferences/api-keys': typeof PreferencesApiKeysRoute
  '/preferences/updates': typeof PreferencesUpdatesRoute
  '/preferences/': typeof PreferencesIndexRoute
  '/recording-popup/': typeof RecordingPopupIndexRoute
}
export interface FileRoutesByTo {
  '/preferences/about': typeof PreferencesAboutRoute
  '/preferences/api-keys': typeof PreferencesApiKeysRoute
  '/preferences/updates': typeof PreferencesUpdatesRoute
  '/preferences': typeof PreferencesIndexRoute
  '/recording-popup': typeof RecordingPopupIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/preferences': typeof PreferencesRouteRouteWithChildren
  '/recording-popup': typeof RecordingPopupRouteRouteWithChildren
  '/preferences/about': typeof PreferencesAboutRoute
  '/preferences/api-keys': typeof PreferencesApiKeysRoute
  '/preferences/updates': typeof PreferencesUpdatesRoute
  '/preferences/': typeof PreferencesIndexRoute
  '/recording-popup/': typeof RecordingPopupIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/preferences'
    | '/recording-popup'
    | '/preferences/about'
    | '/preferences/api-keys'
    | '/preferences/updates'
    | '/preferences/'
    | '/recording-popup/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/preferences/about'
    | '/preferences/api-keys'
    | '/preferences/updates'
    | '/preferences'
    | '/recording-popup'
  id:
    | '__root__'
    | '/preferences'
    | '/recording-popup'
    | '/preferences/about'
    | '/preferences/api-keys'
    | '/preferences/updates'
    | '/preferences/'
    | '/recording-popup/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PreferencesRouteRoute: typeof PreferencesRouteRouteWithChildren
  RecordingPopupRouteRoute: typeof RecordingPopupRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recording-popup': {
      id: '/recording-popup'
      path: '/recording-popup'
      fullPath: '/recording-popup'
      preLoaderRoute: typeof RecordingPopupRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preferences': {
      id: '/preferences'
      path: '/preferences'
      fullPath: '/preferences'
      preLoaderRoute: typeof PreferencesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recording-popup/': {
      id: '/recording-popup/'
      path: '/'
      fullPath: '/recording-popup/'
      preLoaderRoute: typeof RecordingPopupIndexRouteImport
      parentRoute: typeof RecordingPopupRouteRoute
    }
    '/preferences/': {
      id: '/preferences/'
      path: '/'
      fullPath: '/preferences/'
      preLoaderRoute: typeof PreferencesIndexRouteImport
      parentRoute: typeof PreferencesRouteRoute
    }
    '/preferences/updates': {
      id: '/preferences/updates'
      path: '/updates'
      fullPath: '/preferences/updates'
      preLoaderRoute: typeof PreferencesUpdatesRouteImport
      parentRoute: typeof PreferencesRouteRoute
    }
    '/preferences/api-keys': {
      id: '/preferences/api-keys'
      path: '/api-keys'
      fullPath: '/preferences/api-keys'
      preLoaderRoute: typeof PreferencesApiKeysRouteImport
      parentRoute: typeof PreferencesRouteRoute
    }
    '/preferences/about': {
      id: '/preferences/about'
      path: '/about'
      fullPath: '/preferences/about'
      preLoaderRoute: typeof PreferencesAboutRouteImport
      parentRoute: typeof PreferencesRouteRoute
    }
  }
}

interface PreferencesRouteRouteChildren {
  PreferencesAboutRoute: typeof PreferencesAboutRoute
  PreferencesApiKeysRoute: typeof PreferencesApiKeysRoute
  PreferencesUpdatesRoute: typeof PreferencesUpdatesRoute
  PreferencesIndexRoute: typeof PreferencesIndexRoute
}

const PreferencesRouteRouteChildren: PreferencesRouteRouteChildren = {
  PreferencesAboutRoute: PreferencesAboutRoute,
  PreferencesApiKeysRoute: PreferencesApiKeysRoute,
  PreferencesUpdatesRoute: PreferencesUpdatesRoute,
  PreferencesIndexRoute: PreferencesIndexRoute,
}

const PreferencesRouteRouteWithChildren =
  PreferencesRouteRoute._addFileChildren(PreferencesRouteRouteChildren)

interface RecordingPopupRouteRouteChildren {
  RecordingPopupIndexRoute: typeof RecordingPopupIndexRoute
}

const RecordingPopupRouteRouteChildren: RecordingPopupRouteRouteChildren = {
  RecordingPopupIndexRoute: RecordingPopupIndexRoute,
}

const RecordingPopupRouteRouteWithChildren =
  RecordingPopupRouteRoute._addFileChildren(RecordingPopupRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PreferencesRouteRoute: PreferencesRouteRouteWithChildren,
  RecordingPopupRouteRoute: RecordingPopupRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
