/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecordingPopupRouteRouteImport } from './routes/recording-popup/route'
import { Route as PreferencesRouteRouteImport } from './routes/preferences/route'
import { Route as OnboardingRouteRouteImport } from './routes/onboarding/route'
import { Route as RecordingPopupIndexRouteImport } from './routes/recording-popup/index'
import { Route as PreferencesIndexRouteImport } from './routes/preferences/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as PreferencesUpdatesRouteImport } from './routes/preferences/updates'
import { Route as PreferencesHotkeysRouteImport } from './routes/preferences/hotkeys'
import { Route as PreferencesApiKeysRouteImport } from './routes/preferences/api-keys'
import { Route as PreferencesAboutRouteImport } from './routes/preferences/about'
import { Route as OnboardingWelcomeRouteImport } from './routes/onboarding/welcome'
import { Route as OnboardingTriggerKeyRouteImport } from './routes/onboarding/trigger-key'
import { Route as OnboardingFnSpaceRouteImport } from './routes/onboarding/fn-space'
import { Route as OnboardingFnHoldRouteImport } from './routes/onboarding/fn-hold'
import { Route as OnboardingCompleteRouteImport } from './routes/onboarding/complete'
import { Route as OnboardingApiKeysRouteImport } from './routes/onboarding/api-keys'
import { Route as OnboardingAccessibilityRouteImport } from './routes/onboarding/accessibility'

const RecordingPopupRouteRoute = RecordingPopupRouteRouteImport.update({
  id: '/recording-popup',
  path: '/recording-popup',
  getParentRoute: () => rootRouteImport,
} as any)
const PreferencesRouteRoute = PreferencesRouteRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRouteRoute = OnboardingRouteRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordingPopupIndexRoute = RecordingPopupIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RecordingPopupRouteRoute,
} as any)
const PreferencesIndexRoute = PreferencesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PreferencesRouteRoute,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const PreferencesUpdatesRoute = PreferencesUpdatesRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => PreferencesRouteRoute,
} as any)
const PreferencesHotkeysRoute = PreferencesHotkeysRouteImport.update({
  id: '/hotkeys',
  path: '/hotkeys',
  getParentRoute: () => PreferencesRouteRoute,
} as any)
const PreferencesApiKeysRoute = PreferencesApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => PreferencesRouteRoute,
} as any)
const PreferencesAboutRoute = PreferencesAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PreferencesRouteRoute,
} as any)
const OnboardingWelcomeRoute = OnboardingWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingTriggerKeyRoute = OnboardingTriggerKeyRouteImport.update({
  id: '/trigger-key',
  path: '/trigger-key',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingFnSpaceRoute = OnboardingFnSpaceRouteImport.update({
  id: '/fn-space',
  path: '/fn-space',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingFnHoldRoute = OnboardingFnHoldRouteImport.update({
  id: '/fn-hold',
  path: '/fn-hold',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingCompleteRoute = OnboardingCompleteRouteImport.update({
  id: '/complete',
  path: '/complete',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingApiKeysRoute = OnboardingApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingAccessibilityRoute = OnboardingAccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => OnboardingRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/preferences': typeof PreferencesRouteRouteWithChildren
  '/recording-popup': typeof RecordingPopupRouteRouteWithChildren
  '/onboarding/accessibility': typeof OnboardingAccessibilityRoute
  '/onboarding/api-keys': typeof OnboardingApiKeysRoute
  '/onboarding/complete': typeof OnboardingCompleteRoute
  '/onboarding/fn-hold': typeof OnboardingFnHoldRoute
  '/onboarding/fn-space': typeof OnboardingFnSpaceRoute
  '/onboarding/trigger-key': typeof OnboardingTriggerKeyRoute
  '/onboarding/welcome': typeof OnboardingWelcomeRoute
  '/preferences/about': typeof PreferencesAboutRoute
  '/preferences/api-keys': typeof PreferencesApiKeysRoute
  '/preferences/hotkeys': typeof PreferencesHotkeysRoute
  '/preferences/updates': typeof PreferencesUpdatesRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/preferences/': typeof PreferencesIndexRoute
  '/recording-popup/': typeof RecordingPopupIndexRoute
}
export interface FileRoutesByTo {
  '/onboarding/accessibility': typeof OnboardingAccessibilityRoute
  '/onboarding/api-keys': typeof OnboardingApiKeysRoute
  '/onboarding/complete': typeof OnboardingCompleteRoute
  '/onboarding/fn-hold': typeof OnboardingFnHoldRoute
  '/onboarding/fn-space': typeof OnboardingFnSpaceRoute
  '/onboarding/trigger-key': typeof OnboardingTriggerKeyRoute
  '/onboarding/welcome': typeof OnboardingWelcomeRoute
  '/preferences/about': typeof PreferencesAboutRoute
  '/preferences/api-keys': typeof PreferencesApiKeysRoute
  '/preferences/hotkeys': typeof PreferencesHotkeysRoute
  '/preferences/updates': typeof PreferencesUpdatesRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/preferences': typeof PreferencesIndexRoute
  '/recording-popup': typeof RecordingPopupIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/preferences': typeof PreferencesRouteRouteWithChildren
  '/recording-popup': typeof RecordingPopupRouteRouteWithChildren
  '/onboarding/accessibility': typeof OnboardingAccessibilityRoute
  '/onboarding/api-keys': typeof OnboardingApiKeysRoute
  '/onboarding/complete': typeof OnboardingCompleteRoute
  '/onboarding/fn-hold': typeof OnboardingFnHoldRoute
  '/onboarding/fn-space': typeof OnboardingFnSpaceRoute
  '/onboarding/trigger-key': typeof OnboardingTriggerKeyRoute
  '/onboarding/welcome': typeof OnboardingWelcomeRoute
  '/preferences/about': typeof PreferencesAboutRoute
  '/preferences/api-keys': typeof PreferencesApiKeysRoute
  '/preferences/hotkeys': typeof PreferencesHotkeysRoute
  '/preferences/updates': typeof PreferencesUpdatesRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/preferences/': typeof PreferencesIndexRoute
  '/recording-popup/': typeof RecordingPopupIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/onboarding'
    | '/preferences'
    | '/recording-popup'
    | '/onboarding/accessibility'
    | '/onboarding/api-keys'
    | '/onboarding/complete'
    | '/onboarding/fn-hold'
    | '/onboarding/fn-space'
    | '/onboarding/trigger-key'
    | '/onboarding/welcome'
    | '/preferences/about'
    | '/preferences/api-keys'
    | '/preferences/hotkeys'
    | '/preferences/updates'
    | '/onboarding/'
    | '/preferences/'
    | '/recording-popup/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/onboarding/accessibility'
    | '/onboarding/api-keys'
    | '/onboarding/complete'
    | '/onboarding/fn-hold'
    | '/onboarding/fn-space'
    | '/onboarding/trigger-key'
    | '/onboarding/welcome'
    | '/preferences/about'
    | '/preferences/api-keys'
    | '/preferences/hotkeys'
    | '/preferences/updates'
    | '/onboarding'
    | '/preferences'
    | '/recording-popup'
  id:
    | '__root__'
    | '/onboarding'
    | '/preferences'
    | '/recording-popup'
    | '/onboarding/accessibility'
    | '/onboarding/api-keys'
    | '/onboarding/complete'
    | '/onboarding/fn-hold'
    | '/onboarding/fn-space'
    | '/onboarding/trigger-key'
    | '/onboarding/welcome'
    | '/preferences/about'
    | '/preferences/api-keys'
    | '/preferences/hotkeys'
    | '/preferences/updates'
    | '/onboarding/'
    | '/preferences/'
    | '/recording-popup/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  OnboardingRouteRoute: typeof OnboardingRouteRouteWithChildren
  PreferencesRouteRoute: typeof PreferencesRouteRouteWithChildren
  RecordingPopupRouteRoute: typeof RecordingPopupRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recording-popup': {
      id: '/recording-popup'
      path: '/recording-popup'
      fullPath: '/recording-popup'
      preLoaderRoute: typeof RecordingPopupRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preferences': {
      id: '/preferences'
      path: '/preferences'
      fullPath: '/preferences'
      preLoaderRoute: typeof PreferencesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recording-popup/': {
      id: '/recording-popup/'
      path: '/'
      fullPath: '/recording-popup/'
      preLoaderRoute: typeof RecordingPopupIndexRouteImport
      parentRoute: typeof RecordingPopupRouteRoute
    }
    '/preferences/': {
      id: '/preferences/'
      path: '/'
      fullPath: '/preferences/'
      preLoaderRoute: typeof PreferencesIndexRouteImport
      parentRoute: typeof PreferencesRouteRoute
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/preferences/updates': {
      id: '/preferences/updates'
      path: '/updates'
      fullPath: '/preferences/updates'
      preLoaderRoute: typeof PreferencesUpdatesRouteImport
      parentRoute: typeof PreferencesRouteRoute
    }
    '/preferences/hotkeys': {
      id: '/preferences/hotkeys'
      path: '/hotkeys'
      fullPath: '/preferences/hotkeys'
      preLoaderRoute: typeof PreferencesHotkeysRouteImport
      parentRoute: typeof PreferencesRouteRoute
    }
    '/preferences/api-keys': {
      id: '/preferences/api-keys'
      path: '/api-keys'
      fullPath: '/preferences/api-keys'
      preLoaderRoute: typeof PreferencesApiKeysRouteImport
      parentRoute: typeof PreferencesRouteRoute
    }
    '/preferences/about': {
      id: '/preferences/about'
      path: '/about'
      fullPath: '/preferences/about'
      preLoaderRoute: typeof PreferencesAboutRouteImport
      parentRoute: typeof PreferencesRouteRoute
    }
    '/onboarding/welcome': {
      id: '/onboarding/welcome'
      path: '/welcome'
      fullPath: '/onboarding/welcome'
      preLoaderRoute: typeof OnboardingWelcomeRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/trigger-key': {
      id: '/onboarding/trigger-key'
      path: '/trigger-key'
      fullPath: '/onboarding/trigger-key'
      preLoaderRoute: typeof OnboardingTriggerKeyRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/fn-space': {
      id: '/onboarding/fn-space'
      path: '/fn-space'
      fullPath: '/onboarding/fn-space'
      preLoaderRoute: typeof OnboardingFnSpaceRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/fn-hold': {
      id: '/onboarding/fn-hold'
      path: '/fn-hold'
      fullPath: '/onboarding/fn-hold'
      preLoaderRoute: typeof OnboardingFnHoldRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/complete': {
      id: '/onboarding/complete'
      path: '/complete'
      fullPath: '/onboarding/complete'
      preLoaderRoute: typeof OnboardingCompleteRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/api-keys': {
      id: '/onboarding/api-keys'
      path: '/api-keys'
      fullPath: '/onboarding/api-keys'
      preLoaderRoute: typeof OnboardingApiKeysRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/accessibility': {
      id: '/onboarding/accessibility'
      path: '/accessibility'
      fullPath: '/onboarding/accessibility'
      preLoaderRoute: typeof OnboardingAccessibilityRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
  }
}

interface OnboardingRouteRouteChildren {
  OnboardingAccessibilityRoute: typeof OnboardingAccessibilityRoute
  OnboardingApiKeysRoute: typeof OnboardingApiKeysRoute
  OnboardingCompleteRoute: typeof OnboardingCompleteRoute
  OnboardingFnHoldRoute: typeof OnboardingFnHoldRoute
  OnboardingFnSpaceRoute: typeof OnboardingFnSpaceRoute
  OnboardingTriggerKeyRoute: typeof OnboardingTriggerKeyRoute
  OnboardingWelcomeRoute: typeof OnboardingWelcomeRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

const OnboardingRouteRouteChildren: OnboardingRouteRouteChildren = {
  OnboardingAccessibilityRoute: OnboardingAccessibilityRoute,
  OnboardingApiKeysRoute: OnboardingApiKeysRoute,
  OnboardingCompleteRoute: OnboardingCompleteRoute,
  OnboardingFnHoldRoute: OnboardingFnHoldRoute,
  OnboardingFnSpaceRoute: OnboardingFnSpaceRoute,
  OnboardingTriggerKeyRoute: OnboardingTriggerKeyRoute,
  OnboardingWelcomeRoute: OnboardingWelcomeRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
}

const OnboardingRouteRouteWithChildren = OnboardingRouteRoute._addFileChildren(
  OnboardingRouteRouteChildren,
)

interface PreferencesRouteRouteChildren {
  PreferencesAboutRoute: typeof PreferencesAboutRoute
  PreferencesApiKeysRoute: typeof PreferencesApiKeysRoute
  PreferencesHotkeysRoute: typeof PreferencesHotkeysRoute
  PreferencesUpdatesRoute: typeof PreferencesUpdatesRoute
  PreferencesIndexRoute: typeof PreferencesIndexRoute
}

const PreferencesRouteRouteChildren: PreferencesRouteRouteChildren = {
  PreferencesAboutRoute: PreferencesAboutRoute,
  PreferencesApiKeysRoute: PreferencesApiKeysRoute,
  PreferencesHotkeysRoute: PreferencesHotkeysRoute,
  PreferencesUpdatesRoute: PreferencesUpdatesRoute,
  PreferencesIndexRoute: PreferencesIndexRoute,
}

const PreferencesRouteRouteWithChildren =
  PreferencesRouteRoute._addFileChildren(PreferencesRouteRouteChildren)

interface RecordingPopupRouteRouteChildren {
  RecordingPopupIndexRoute: typeof RecordingPopupIndexRoute
}

const RecordingPopupRouteRouteChildren: RecordingPopupRouteRouteChildren = {
  RecordingPopupIndexRoute: RecordingPopupIndexRoute,
}

const RecordingPopupRouteRouteWithChildren =
  RecordingPopupRouteRoute._addFileChildren(RecordingPopupRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  OnboardingRouteRoute: OnboardingRouteRouteWithChildren,
  PreferencesRouteRoute: PreferencesRouteRouteWithChildren,
  RecordingPopupRouteRoute: RecordingPopupRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
