/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecordingPopupRouteImport } from './routes/recording-popup'
import { Route as PreferencesRouteImport } from './routes/preferences'
import { Route as IndexRouteImport } from './routes/index'

const RecordingPopupRoute = RecordingPopupRouteImport.update({
  id: '/recording-popup',
  path: '/recording-popup',
  getParentRoute: () => rootRouteImport,
} as any)
const PreferencesRoute = PreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/preferences': typeof PreferencesRoute
  '/recording-popup': typeof RecordingPopupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/preferences': typeof PreferencesRoute
  '/recording-popup': typeof RecordingPopupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/preferences': typeof PreferencesRoute
  '/recording-popup': typeof RecordingPopupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/preferences' | '/recording-popup'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/preferences' | '/recording-popup'
  id: '__root__' | '/' | '/preferences' | '/recording-popup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PreferencesRoute: typeof PreferencesRoute
  RecordingPopupRoute: typeof RecordingPopupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recording-popup': {
      id: '/recording-popup'
      path: '/recording-popup'
      fullPath: '/recording-popup'
      preLoaderRoute: typeof RecordingPopupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preferences': {
      id: '/preferences'
      path: '/preferences'
      fullPath: '/preferences'
      preLoaderRoute: typeof PreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PreferencesRoute: PreferencesRoute,
  RecordingPopupRoute: RecordingPopupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
